### ISSUE TITLE
Google Cloud Build : delete-default-gateway-routes.sh: not found

### ISSUE THREAD

**Issue by komasoftware** [terraform-google-modules/terraform-google-project-factory#323]
I am running terraform init, plan, apply, destroy for every release of a in-house module using GCP Cloud Build as you can see from below cloudbuild.yaml file.
This was working fine until I started running into below issue where **the default gateway deletion script is not found** when running **terraform apply**. This only happens when running on Cloud Build, I cannot reproduce the problem on my local machine.

Any idea ?

 **/bin/sh: .terraform/modules/xpn/terraform-google-modules-terraform-google-network-e273b5e/scripts/delete-default-gateway-routes.sh: not found**

```
- steps
  # download service account key of tvh-terraform-admin
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://XXXXXXXXXX/secrets.json', 'secrets.json']
  # setup test environment
  - name: bash
    args: ["bash", "-c", "mv backend.tf.test backend.tf"]
  # init test environment
  - name: hashicorp/terraform:light
    args: ["init"]
    env:
      - "GOOGLE_APPLICATION_CREDENTIALS=secrets.json"
  # plan test environment
  - name: hashicorp/terraform:light
    args: ["plan", "-input=false", "-var-file=variables.test.tfvars", "-refresh=true", "-out=tf-modules-environment.test.tfplan"]
    env:
      - "GOOGLE_APPLICATION_CREDENTIALS=secrets.json"
      - "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=secrets.json"
  # apply test environment
  - name: hashicorp/terraform:light
    args: ["apply", "-auto-approve", "tf-modules-environment.test.tfplan"]
    env:
      - "GOOGLE_APPLICATION_CREDENTIALS=secrets.json"
      - "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=secrets.json"
  - name: hashicorp/terraform:light
    args: ["destroy",  "-auto-approve", "-var-file=variables.test.tfvars"]
    env:
      - "GOOGLE_APPLICATION_CREDENTIALS=secrets.json"
      - "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=secrets.json"

```
Error: Error running command '.terraform/modules/xpn/terraform-google-modules-terraform-google-network-e273b5e/scripts/delete-default-gateway-routes.sh xpn-terratest-04 terratest-xpn': exit status 127. Output: /bin/sh: .terraform/modules/xpn/terraform-google-modules-terraform-google-network-e273b5e/scripts/delete-default-gateway-routes.sh: not found

![Selection_999(476)](https://user-images.githubusercontent.com/482152/69734095-b620eb80-112e-11ea-89c6-2b617470d901.jpg)
