### ISSUE TITLE
Preconditions check fails for billing permission

### ISSUE THREAD

**Issue by jwp23** [terraform-google-modules/terraform-google-project-factory#423]
When I use Cloud Build to run the project factory, I get the following error
`Step #3 - "tf apply":  Error: failed pre-requisites: missing permission on "billingAccounts/<billing account redacted>": billing.resourceAssociations.create`

I went through the troubleshooting steps. In the Account Management screen, my billing account shows the organization is my domain. The Cloud Build service account is attached as a Billing Account User for my billing account.

I'm using version 8.0.1 of this module.
Cloud Build is using Terraform version 0.12.26

**Comment by morgante** [comment]
Can you share your Terraform and Cloud Build configs?

**Comment by jwp23** [comment]
I'm creating a demo to run Cloud Build to deploy a project using a module that wraps around the project factory and that accepts the project name as a substitution in the Cloud Build run. The Cloud Build config is
```yaml
steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: 'tf init'
    name: 'hashicorp/terraform:0.12.26'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init || exit 1

  # [START tf-plan]
  - id: 'tf plan'
    name: 'hashicorp/terraform:0.12.26'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_VAR_project_name=${_PROJECT_NAME}
        terraform plan || exit 1
  # [END tf-plan]

  # [START tf-apply]
  - id: 'tf apply'
    name: 'hashicorp/terraform:0.12.26'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_VAR_project_name=${_PROJECT_NAME}
        terraform apply -auto-approve
# [END tf-apply]
```

The Terraform config is
```hcl
provider "google" {
  version = "~> 3.23.0"
}

terraform {
  backend "gcs" {
    bucket = "<redacted>"
    prefix = "<redacted>/cloudbuild-demo-project-factory"
  }
}

variable "project_name" {
  description = "The name of the project. The project id will have a random suffix attached to the project name"
}

module "project" {
  source                  = "terraform-google-modules/project-factory/google"
  version                 = "~> 8.0.1"
  random_project_id       = true
  name                    = var.project_name
  org_id                  = "<redacted>"
  billing_account         = "<redacted>"
  default_service_account = true
}
```

The command I use to trigger the Cloud Build is
`gcloud builds submit . --config=cloudbuild.yaml --substitutions=_PROJECT_NAME="foobar"`
